name: PreVisitedTeleport
version: 3.0.0
description: A teleportation plugin that requires players to visit a location before they can teleport there.
author: Draeke_Forther
main: com.PromethiaRP.Draeke.PreVisit.PreVisit

commands:
 ft:
  description: Teleport to a previously visited location.
  usage: /<command> <WarpName>
 warps:
  description: Displays a list of available locations to teleport to.
  usage: /<command> [WarpName]
 svwarp:
  description: Creates a warp for players to teleport to.
  usage: /<command> [Size] <WarpName>
 dvwarp:
  description: Deletes a warp.
  usage: /<command> <WarpName>
 energy:
  description: Displays the energy that a Player currently has.
  usage: /<command>

permissions:
 previsit.*:
  description: Gives access to all warps and all PreVisit commands.
  children:
   previsit.svwarp: true
   previsit.dvwarp: true
   previsit.useenergy: false
   previsit.combatwait: false
   previsit.allwarps: true
   previsit.giveenergy: true
   previsit.ft: true
   previsit.worldchange: true
  default: op
 previsit.svwarp:
  description: Players can create warps if set.
  default: op
 previsit.dvwarp:
  description: Players can delete warps if set.
  default: op
 previsit.useenergy:
  description: Players must use energy to fast travel if set.
  default: true
 previsit.combatwait:
  description: Players must exit combat to fast travel if set.
  default: true
 previsit.allwarps:
  description: Players can fast travel unconditionally if set.
  default: false
 previsit.giveenergy:
  description: Players can give energy to others if set.
  default: op
 previsit.ft:
  description: Players can fast travel if set.
  default: true
 previsit.worldchange:
  description: Players can travel across worlds if set.
  default: op